# Generated by Django 3.0.7 on 2020-07-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={},
        ),
    ]
