# Generated by Django 3.0.7 on 2020-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='check_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
