# Generated by Django 3.0.7 on 2020-07-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_auto_20200709_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('client', 'clients_permission'),),
                'managed': False,
            },
        ),
    ]
