# Generated by Django 3.0.7 on 2020-07-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_orders_check_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='check_token',
        ),
    ]
