# Generated by Django 3.0.7 on 2020-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_auto_20200716_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
