# Generated by Django 3.0.7 on 2020-08-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_remove_orders_check_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('client', 'clients_permission'), ('employee', 'employee_permission'))},
        ),
    ]
