# Generated by Django 3.0.7 on 2020-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_auto_20200822_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='reg_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
