# Generated by Django 3.0.7 on 2020-07-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_clients_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
    ]
