# Generated by Django 3.0.7 on 2020-09-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_Cars_reg_is_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('authorisation', models.BooleanField(default=False)),
            ],
        ),
    ]
