# Generated by Django 3.0.7 on 2020-07-22 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_auto_20200721_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='discount_code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(999), django.core.validators.MinValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_rental.Cars')),
            ],
        ),
    ]
