# Generated by Django 3.0.7 on 2020-09-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segments',
            name='name',
            field=models.CharField(help_text='Select type of car', max_length=32),
        ),
    ]
