# Generated by Django 3.0.7 on 2020-07-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_auto_20200722_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='segment',
            new_name='car',
        ),
    ]
